
create table links (id int8 generated by default as identity, full_link varchar(255), short_link varchar(255), primary key (id));
create table links (id int8 generated by default as identity, full_link varchar(255), short_link varchar(255), primary key (id));
create table links (id int8 generated by default as identity, full_link varchar(255), short_link varchar(255), primary key (id));
